### ISSUE TITLE
Stack Overflow?

### ISSUE THREAD

**Issue by mariyahhaq** [picrin/practicingFoundations#3]
![capture](https://cloud.githubusercontent.com/assets/15628611/10996341/1bafb164-847c-11e5-95b1-134cc09fac3e.PNG)
 Im pretty sure the code is right bc I have checked it... :)

**Comment by picrin** [comment]
Hi Maria, sorry I'm getting back so late, I've set up an e-mail notification for those issues now, I should more prompt next time

The problem with your code is that you have infinite recursion, which means you create stack frames until visual basic runs out of space in your computer and your application crashes.

This is because below the line which starts `Dim e2` you call the function you're currently in, that is testSwapLeft().

What you meant to do was swapLeft() instead!
